on:
  schedule:
    - cron: "0 */4 * * *"
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/e2e-cra-storybook-workflow.yml
      - scripts/e2e-setup-ci.sh

name: "E2E CRA Storybook"
jobs:
  chore:
    name: "Validating Create-React-App"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master

      - name: "Use Node.js 10.x"
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: "Build the standard bundle"
        run: |
          node ./scripts/run-yarn.js build:cli

      - name: "Running the integration test"
        run: |
          source scripts/e2e-setup-ci.sh
          yarn dlx create-react-app my-cra && cd my-cra
          yarn dlx -p @storybook/cli sb init
          yarn build
          yarn storybook

      - name: "Running the TypeScript integration test"
        run: |
          source scripts/e2e-setup-ci.sh
          yarn dlx create-react-app my-cra-ts --template typescript && cd my-cra-ts
          yarn dlx -p @storybook/cli sb init
          yarn build
          yarn storybook
